env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[332ff46ee7092de3c120a9f44eaa4b7a980046f3cdaabb607172c73fdc7cbbb25b961935e14eb9efdb67fdc24cb5e6d0]"
    CHATID: "ENCRYPTED[7bbad666b9f82739306e9e894632462f93e0a9df187bf7f8070aa7b16819404ca6ae454f26245d99ce71aa56a7d8a228]"
    API_BOT: "ENCRYPTED[3db75af810d60ffaffdcf4e74480cb878ccd3c00607b3f2a5bdcc6e6e92509911aad2d1c2be8c726f943ac0041e0fbfd]"

task:
    name: ManoharSingh
    timeout_in: 240m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 30G
    download_ccache_background_script:
      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
