#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://server.nippon.workers.dev/ccache/ci2/cr_ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
time tar xf cr_ccache.tar.gz
find cr_ccache.tar.gz -delete
