#!/bin/bash

MANIFEST=git://github.com/crdroidandroid/android.git
BRANCH=11.0

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name adi153
git config --global user.email singhmanohar6699@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
find hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/media .repo/ -delete
git clone https://github.com/LineageOS/android_hardware_qcom_audio --single-branch -b lineage-18.1-caf-msm8996 hardware/qcom-caf/msm8996/audio --depth=1
git clone https://github.com/LineageOS/android_hardware_qcom_media --single-branch -b lineage-18.1-caf-msm8996 hardware/qcom-caf/msm8996/media --depth=1

git clone https://github.com/adi153/device_xiaomi_rolex --single-branch -b cr-11.0 device/xiaomi/rolex --depth=1
git clone https://github.com/adi153/vendor_xiaomi_rolex --single-branch -b cr-11.0 vendor/xiaomi/rolex --depth=1
git clone https://github.com/Thagoo/platform_kernel_xiaomi_msm8917 --single-branch -b r kernel/xiaomi/msm8917 --depth=1
